import os
from pathlib import Path

# ---- WandB Settings ----
WANDB_PROJECT = "ibmt-mahjong"
WANDB_ENTITY = None

# ---- Path Settings ----
_CONFIG_FILEPATH = Path(__file__).resolve()
SRC_ROOT = _CONFIG_FILEPATH.parent
PROJECT_ROOT = SRC_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data"
MJLOG_DIR = DATA_DIR / "mjlogs"
JSON_LOGS_DIR = DATA_DIR / "json_logs"
PROCESSED_DIR = DATA_DIR / "processed"
MODEL_DIR = PROJECT_ROOT / "models"
RESULTS_DIR = PROJECT_ROOT / "results"
EVAL_ACTION_CSV = RESULTS_DIR / "eval_action.csv"
EVAL_INTENT_CSV = RESULTS_DIR / "eval_intent.csv"
EVAL_BELIEF_CSV = RESULTS_DIR / "eval_belief.csv"

# ---- Execution Settings ----
SEED = 42
NUM_PROCESSES = 8
SUBPROCESS_TIMEOUT = 60
PARALLEL_BATCH_SIZE = 100

# ---- Dataset Settings ----
TRAIN_CHUNK_SIZE = int(1e5)
TARGET_TRAIN_DATA = int(1.5e7)
TARGET_VALID_DATA = int(1e4)
TARGET_TEST_DATA = int(5e4)
NUM_YAKU = 55
NUM_SHANTEN_CLASSES = 7

# ---- Training Settings ----
BATCH_SIZE = 1024
LEARNING_RATE = 5e-4
MAX_EPOCHS = 100
EARLY_STOPPING_PATIENCE = 5
LAMBDA_ACTION = 1.0
LAMBDA_INTENT = 0.2
LAMBDA_BELIEF = 0.2

# ---- CNN Settings ----
CNN_IMAGE_SIZE = (34, 1)
CNN_CHANNELS = 350
CNN_NUM_CLASSES = 34
CNN_NUM_BLOCK = 50
CNN_HIDDEN_DIM = 256
CNN_KERNEL_SIZE = (3, 1)
CNN_STRIDE = (1, 1)
CNN_PADDING = (1, 0)

# ---- Transformer Settings ----
TRANS_SEQ_LEN = 34
TRANS_INPUT_DIM = 350
TRANS_NUM_CLASSES = 34
TRANS_EMB_DIM = 256
TRANS_NUM_HEADS = 8
TRANS_NUM_LAYERS = 24
TRANS_DIM_FEEDFORWARD = 1024
TRANS_DROPOUT = 0.1

# ---- MST Settings ----
MST_SEQ_LEN = 34
MST_INPUT_DIM = 350
MST_NUM_CLASSES = 34
MST_EMB_DIM = 256
MST_NUM_HEADS = 8
MST_NUM_LAYERS = 24
MST_DIM_FEEDFORWARD = 1024
MST_DROPOUT = 0.1

# ---- IBMT Intent Settings ----
IBMT_INTENT_SEQ_LEN = 34
IBMT_INTENT_INPUT_DIM = 350
IBMT_INTENT_NUM_CLASSES = 34
IBMT_INTENT_EMB_DIM = 256
IBMT_INTENT_NUM_HEADS = 8
IBMT_INTENT_NUM_LAYERS = 24
IBMT_INTENT_DIM_FEEDFORWARD = 1024
IBMT_INTENT_DROPOUT = 0.1

# ---- IBMT Belief Settings ----
IBMT_BELIEF_SEQ_LEN = 34
IBMT_BELIEF_INPUT_DIM = 350
IBMT_BELIEF_NUM_CLASSES = 34
IBMT_BELIEF_EMB_DIM = 256
IBMT_BELIEF_NUM_HEADS = 8
IBMT_BELIEF_NUM_LAYERS = 24
IBMT_BELIEF_DIM_FEEDFORWARD = 1024
IBMT_BELIEF_DROPOUT = 0.1

# ---- IBMT Full Settings ----
IBMT_FULL_SEQ_LEN = 34
IBMT_FULL_INPUT_DIM = 350
IBMT_FULL_NUM_CLASSES = 34
IBMT_FULL_EMB_DIM = 256
IBMT_FULL_NUM_HEADS = 8
IBMT_FULL_NUM_LAYERS = 24
IBMT_FULL_DIM_FEEDFORWARD = 1024
IBMT_FULL_DROPOUT = 0.1
